pipeline {
    agent any

    stages {
        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Setup Python Environment') {
            steps {
                // Remove old venv if exists, then create new one
                sh '''
                    rm -rf venv
                    python3 -m venv venv
                '''
            }
        }

        stage('Install Dependencies') {
            steps {
                // Upgrade pip and install requirements
                sh '''
                    ./venv/bin/pip install --upgrade pip
                    ./venv/bin/pip install -r requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                // Run unittest, generate XML reports for Jenkins
                sh '''
                    mkdir -p tests/reports
                    ./venv/bin/python -m unittest discover -s tests -p '*_test.py' -v > tests/reports/tests_output.log || true
                '''
            }
            post {
                always {
                    // Archive test output logs (optional)
                    archiveArtifacts artifacts: 'tests/reports/tests_output.log', allowEmptyArchive: true

                    // If you have XML reports generated by your tests, use this to publish them:
                    // junit 'tests/reports/*.xml'

                    // If not, you can just publish the console logs as artifacts
                }
            }
        }
    }
}
